util_barrier:
    image: goldbuick/util_barrier
    ports:
        - "8888:8888"
        - "8080:8080"
        - "7154:7154"
        - "26154:26154"
    volumes:
        - "$PWD:/var/nginx"
    links:
        - rethinkdb
        - private_proxy
        - stem_config_server
        - stem_terminal_server

private_proxy:
    image: jwilder/nginx-proxy
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
        - "127.0.0.1:7080:80"

stem_terminal_server:
    image: goldbuick/stem_terminal_server
    net: "container:stem_config_server"
    ports:
        - "127.0.0.1:16154:26154"

stem_config_server:
    image: goldbuick/stem_config_server
    ports:
        - "127.0.0.1:6154:7154"
    links:
        - rethinkdb

rethinkdb:
    image: rethinkdb
    ports:
        - "127.0.0.1:7777:8080"
        - "127.0.0.1:28015:28015"
        - "127.0.0.1:29015:29015"
    volumes:
        - "$PWD:/data"
